# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               'Malaikannan'
tagline:             'The Deep Learning way of life'
description:         'To Deep Learn or Not to Deep Learn.'
url:                 http://malaikannan.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Malaikannan Sankarasubbu
  url:               https://twitter.com/malai_san
  email:             malai128@gmail.com

# Custom vars
version:             1.0.0
